export { clientRepo } from './client.repository'
export { doctorRepo } from './doctor.repository'
export { fournisseurRepo } from './fournisseur.repository'
export { productRepo, qrcodeRepo, stockAdjustmentRepo } from './product.repository'
export { orderRepo, paymentRepo } from './order.repository'
export { repairRepo } from './repair.repository'
export { repairServiceRepo } from './repair-service.repository'
export { prescriptionRepo } from './prescription.repository'
export { lensBrandRepo } from './lens-brand.repository'
export { userRepo } from './user.repository'
