import type { ReportResponse } from '@/modules/system/reports/dtos/report.dto'

export function toReportResponse(data: Partial<ReportResponse> & { period: string }): ReportResponse {
    return {
        totalClients: data.totalClients,
        totalProducts: data.totalProducts,
        lowStockCount: data.lowStockCount,
        totalOrders: data.totalOrders,
        todayOrders: data.todayOrders,
        pendingRepairs: data.pendingRepairs,
        totalRevenue: data.totalRevenue,
        newClients: data.newClients,
        avgOrderValue: data.avgOrderValue,
        totalProfit: data.totalProfit,
        totalCost: data.totalCost,
        outstandingBalance: data.outstandingBalance,
        revenueByType: data.revenueByType,
        ordersByStatus: data.ordersByStatus,
        topProductsByCategory: data.topProductsByCategory,
        monthlyRevenue: data.monthlyRevenue,
        recentOrders: data.recentOrders,
        topClients: data.topClients,
        salesByPaymentMethod: data.salesByPaymentMethod,
        receivables: data.receivables,
        stockHealth: data.stockHealth,
        repeatClients: data.repeatClients,
        dailyAvgSales: data.dailyAvgSales,
        totalLensBlanks: data.totalLensBlanks,
        lowStockLensBlanks: data.lowStockLensBlanks,
        totalWorkOrders: data.totalWorkOrders,
        pendingWorkOrders: data.pendingWorkOrders,
        completedWorkOrders: data.completedWorkOrders,
        totalOpticianShops: data.totalOpticianShops,
        workOrdersByShop: data.workOrdersByShop,
        monthlyWorkOrders: data.monthlyWorkOrders,
        recentWorkOrders: data.recentWorkOrders,
        workload: data.workload,
        avgTurnaroundDays: data.avgTurnaroundDays,
        breakageRate: data.breakageRate,
        revenueByOptician: data.revenueByOptician,
        lensBlanksLowStock: data.lensBlanksLowStock,
        period: data.period,
    }
}
